# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b38c173dbd08dbe094d861420d6060c9331c0dfea903e434f65f12ca9ece2cf2f57032659a005d9fb9fef0d0bbc68057dca8fca9bbcf1a7b9cf9de7cd30d967a

test:
  secret_key_base: 985e2a490bb4dcea731e82b42f0f0bba0787ce800f4d35dd9904ae229bb2326ee622a10d98ef688d78799085edb470acb7b84544681c7c6de72ed3bda09a1bc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
